# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.8
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - jouni.leino@siili.com
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'create database play;' -U postgres
test:
  adapter: postgresql
  database: play